version: '3.8'

services:
  spring:
    image: docker.io/${DOCKER_USER}/kodanect:${IMAGE_TAG}
    container_name: kodanect-spring-prod
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      IMAGE_TAG: ${IMAGE_TAG}
      JAVA_TOOL_OPTIONS: >
        -Xms256m -Xmx512m
        -XX:+UseG1GC
        -XX:MaxMetaspaceSize=128m
        -Xlog:gc*:file=/app/gc.log:time,uptime,tags
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8080:8080"
    volumes:
      - /home/app/files:/app/files
      - /home/app/uploads:/app/uploads
      - /var/log/kodanect:/app/logs
    network_mode: host