version: '3.8'

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        RUN_MODE: dev
    container_name: kodanect-spring-dev
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
    command: mvn spring-boot:run
    networks:
      - kodanect-net

networks:
  kodanect-net:
    driver: bridge
